### PR TITLE
Check if startsWith exists before setting it

### LINKED ISSUE #13: `startsWith` doesn't work with the two argument form.
The provided polyfill for `startWith` ignores the second argument. The polyfill is installed even if it isn't needed so it breaks any code which expects the two argument version of `startsWith` to work.

Documentation for startsWith:
 https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/startsWith

### PR DESCRIPTION
**Pull request by karthiknadig**
Closes #13

### CODE REVIEW

**Review by huan — APPROVED** [review]
LGTM

**Comment by huan** [comment]
@karthiknadig Thank you very much for the improvement!

However, there's some CI failed. I know it's not related to this PR, but in order to make all the CI green to this PR, could you please fix them as well? Appreciate it.

**Comment by karthiknadig** [comment]
@huan Looks like `nyc` had to be updated. But the latest version of `nyc` does not work on node 6 and below. Additionally, I am explicitly skipping the `startsWith` bits from coverage, since it is not needed any more.

**Comment by huan** [comment]
Thank your very much, merged!

**Comment by karthiknadig** [comment]
@huan Any idea when this will be published?

**Comment by huan** [comment]
I have not checked if our CI can publish the latest code automatically. If it's not, then the publish will depend on how the release strategy is defined by @simonepri

**Comment by simonepri** [comment]
Hi there, sorry for being late and thanks for contributing!

About the CI, I think it was discussed already but the idea is that we need to do a new major release before removing node 4 etc to fix the ci.

So in order for me to release this asap my idea would be to revert all changes but the fix itself.
What do you think?

**Comment by karthiknadig** [comment]
@simonepri Works for me.

**Pull request merged**
